language: c
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
env:
  - LLVM_VERSION=6.0.0

matrix:
  include:
  - os: osx
    compiler: clang
    install:
    - git submodule update --init --recursive
    - curl -o ./llvm.tar.gz http://releases.llvm.org/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-apple-darwin.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-$LLVM_VERSION-x86_64-apple-darwin llvm
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - cmake --build .

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
          - pkg-config
          - libedit-dev
    install:
    - git submodule update --init --recursive
    - curl -o ./llvm.tar.xz http://releases.llvm.org/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - tar xvf ./llvm.tar.xz && mv clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04 llvm
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_FLAGS=-m64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - cmake --build .
