language: c
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
matrix:
  include:
  - os: osx
    compiler: clang
    env: release='faust_tilde_macos64'
    install:
    - git submodule update --init --recursive
    - curl -o ./llvm.tar.gz http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-x86_64-apple-darwin.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-5.0.0-x86_64-apple-darwin llvm
    script:
    - mkdir faust/build/forpd && cd faust/build/forpd
    - cmake .. -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DUSE_LLVM_CONFIG=off -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DLLVM_DIR=./../../llvm/lib/cmake/llvm -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -C../backends/backends.cmake
    - make --quiet
    - mkdir ../../../build && cd ../../../build
    - cmake .. -GXcode -DLLVM_DIR=./llvm/lib/cmake/llvm
    - cmake --build . --config Release
  - os: linux
    compiler: gcc
    env: release='faust_tilde_linux64'
    install:
    - git submodule update --init --recursive
    - sudo apt-get install -y pkg-config libedit-dev
    script:
    - mkdir faust/build/forpd && cd faust/build/forpd
    - cmake .. -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DCMAKE_C_FLAGS=-m64
      -C../backends/backends.cmake
    - make --quiet
    - mkdir ../../../build && cd ../../../build
    - cmake .. -DCMAKE_C_FLAGS=-m64
    - cmake --build . --config Release
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - cp -r faust/libraries external/libs
  - mv external faust_tilde
  - zip -r $release.zip faust_tilde
