language: c
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
matrix:
  include:
  - os: osx
    compiler: clang
    env: ziplib='libfaust_macos64_llvm6.0.0_release'
    install:
    - git submodule update --init --recursive
    - curl -o ./llvm.tar.gz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-6.0.0-x86_64-apple-darwin llvm
    script:
    - mkdir faust/build/forlib && cd faust/build/forlib
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./../../llvm/lib/cmake/llvm -C../backends/all.cmake
    - make staticlib
  - os: osx
    compiler: clang
    env: ziplib='libfaust_macos64_llvm6.0.0_debug'
    install:
    - git submodule update --init --recursive
    - curl -o ./llvm.tar.gz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-6.0.0-x86_64-apple-darwin llvm
    script:
    - mkdir faust/build/forlib && cd faust/build/forlib
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./../../llvm/lib/cmake/llvm -C../backends/all.cmake
    - make staticlib
  - os: linux
    compiler: gcc
    env: ziplib='libfaust_linux64_llvm6.0.0_release'
    install:
    - git submodule update --init --recursive
    - sudo apt-get install -y pkg-config libedit-dev
    - curl -o ./llvm.tar.gz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04 llvm
    script:
    - mkdir faust/build/forlib && cd faust/build/forlib
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DCMAKE_C_FLAGS=-m64 -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./../../llvm/lib/cmake/llvm -C../backends/all.cmake
    - make staticlib
  - os: linux
    compiler: gcc
    env: ziplib='libfaust_linux64_llvm6.0.0_debug'
    install:
    - git submodule update --init --recursive
    - sudo apt-get install -y pkg-config libedit-dev
    - curl -o ./llvm.tar.gz http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - tar zxvf ./llvm.tar.gz && mv clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04 llvm
    script:
    - mkdir faust/build/forlib && cd faust/build/forlib
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DCMAKE_C_FLAGS=-m64 -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./../../llvm/lib/cmake/llvm -C../backends/all.cmake
    - make staticlib
